version: '3'
services:
    api:
        image: hubbeking/deepdream-docker:latest
        depends_on:
          - queue
          - worker
        environment:
          - RABBITMQ_HOST=queue
          - RABBITMQ_PORT=5672
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
          - RABBITMQ_DEFAULT_VHOST=tasks
        ports:
            - "8000:8000"
        restart: unless-stopped
        volumes:
            - ./deepdream/inputs:/opt/deepdream/inputs
            - ./deepdream/outputs:/opt/deepdream/outputs
    queue:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_HOST=queue
            - RABBITMQ_PORT=5672
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_DEFAULT_VHOST=tasks
        restart: unless-stopped
    worker:
        image: hubbeking/deepdream-docker:latest
        command: celery -A tasks worker --loglevel=INFO
        environment:
            - GLOG_minloglevel=2                    # reduced log-level for Caffe (2=WARN, 3=ERROR)
            - EMAIL_SMTP=smtp.gmail.com
            - EMAIL_PORT=587
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASS=${EMAIL_PASS}
            - RABBITMQ_HOST=queue
            - RABBITMQ_PORT=5672
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_DEFAULT_VHOST=tasks
        restart: unless-stopped
        volumes:
            - ./deepdream/inputs:/opt/deepdream/inputs
            - ./deepdream/outputs:/opt/deepdream/outputs
